// Generated by gencpp from file seven_robotics_msgs/AdisImu.msg
// DO NOT EDIT!


#ifndef SEVEN_ROBOTICS_MSGS_MESSAGE_ADISIMU_H
#define SEVEN_ROBOTICS_MSGS_MESSAGE_ADISIMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace seven_robotics_msgs
{
template <class ContainerAllocator>
struct AdisImu_
{
  typedef AdisImu_<ContainerAllocator> Type;

  AdisImu_()
    : header()
    , gyro_latest()
    , accel_latest()  {
      gyro_latest.assign(0.0);

      accel_latest.assign(0.0);
  }
  AdisImu_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gyro_latest()
    , accel_latest()  {
  (void)_alloc;
      gyro_latest.assign(0.0);

      accel_latest.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _gyro_latest_type;
  _gyro_latest_type gyro_latest;

   typedef boost::array<float, 3>  _accel_latest_type;
  _accel_latest_type accel_latest;





  typedef boost::shared_ptr< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> const> ConstPtr;

}; // struct AdisImu_

typedef ::seven_robotics_msgs::AdisImu_<std::allocator<void> > AdisImu;

typedef boost::shared_ptr< ::seven_robotics_msgs::AdisImu > AdisImuPtr;
typedef boost::shared_ptr< ::seven_robotics_msgs::AdisImu const> AdisImuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seven_robotics_msgs::AdisImu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seven_robotics_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'seven_robotics_msgs': ['/home/stach-z97/Seven_ROS/src/seven_robotics_msgs/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8efc0599b85bed911286b8a088cbacc9";
  }

  static const char* value(const ::seven_robotics_msgs::AdisImu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8efc0599b85bed91ULL;
  static const uint64_t static_value2 = 0x1286b8a088cbacc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seven_robotics_msgs/AdisImu";
  }

  static const char* value(const ::seven_robotics_msgs::AdisImu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float32[3] gyro_latest	#gyro latest measurements [rad/s]\n\
float32[3] accel_latest #accel latest measurements [m/s^2]\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seven_robotics_msgs::AdisImu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gyro_latest);
      stream.next(m.accel_latest);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AdisImu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seven_robotics_msgs::AdisImu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seven_robotics_msgs::AdisImu_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gyro_latest[]" << std::endl;
    for (size_t i = 0; i < v.gyro_latest.size(); ++i)
    {
      s << indent << "  gyro_latest[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyro_latest[i]);
    }
    s << indent << "accel_latest[]" << std::endl;
    for (size_t i = 0; i < v.accel_latest.size(); ++i)
    {
      s << indent << "  accel_latest[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accel_latest[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEVEN_ROBOTICS_MSGS_MESSAGE_ADISIMU_H
