<?xml version="1.0"?>
<!--
/****************************************************************************
*	Copyright (C) 2016-2019 Seven Robotics. All rights reserved.
*	Author: Mohammed Talha Arif  <mtalha@sevenrobotics.in>
*   
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*     
*  1. Redistributions of source code must retain the above copyright
*     notice, this list of conditions and the following disclaimer.
*  2. Redistributions in binary form must reproduce the above copyright
*     notice, this list of conditions and the following disclaimer in
*     the documentation and/or other materials provided with the
*     distribution.
* 	3. Neither the name Seven Robotics nor the names of its contributors 
* 		 may be used to endorse or promote products derived from this 
* 		 software without specific prior written permission.
*                
*  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
*  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
*  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
*  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
*  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
*  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
*  OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
*  AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
*  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
*  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
*  POSSIBILITY OF SUCH DAMAGE.
*                                
****************************************************************************/
-->
<robot name="seven" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:arg name="laser_enabled" default="FALSE"/>
	<xacro:arg name="laser_xyz" default="$(optenv SEVEN_LMS2XX_XYZ 0.2750 0.0 0.1267)"/>
	<xacro:arg name="laser_rpy" default="$(optenv SEVEN_LMS2XX_RPY 0.0 0.0 0.0)"/>
	
	<xacro:property name="PI" value="3.14159"/>
	<xacro:include filename="$(find seven_robot_description)/urdf/wheel.urdf.xacro"/>
	<xacro:include filename="$(find seven_robot_description)/urdf/sick.urdf.xacro"/>
	
	<xacro:arg name="robot_namespace" default="/" />

	<!--robot base dimensions: includes the top enclosure
			and flange bearing offsets-->
	<xacro:property name="base_size_x" value="0.6307"/>
	<xacro:property name="base_size_y" value="0.5285"/>
	<xacro:property name="base_size_z" value="0.3305"/>
	

	<!--wheel mounting includes offsets induced by bearings-->
	<xacro:property name="wheel_base" value="0.3440"/>
	<xacro:property name="track_length" value="0.5366"/>
	<xacro:property name="wheel_vertical_offset" value="0.07"/>
	
	<xacro:property name="wheel_width" value="0.08"/>
	<xacro:property name="wheel_radius" value="0.130"/>
	
	<link name="base_link">
		<visual>
						<origin rpy="0 0 ${PI}" xyz="0 0 0"/>
			<geometry>
				<mesh filename="package://seven_robot_description/meshes/robot_base.dae"/>
			</geometry>
		</visual>

		<collision>
		<origin xyz="0 0 ${base_size_z/2}" rpy="0 0 0"/>
		<geometry>
			<box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
		</geometry>
		</collision>
	</link>

	<link name="base_footprint"/>

	<!--This is the footprint of our base which lies on the ground at all times-->
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="base_footprint"/>
	</joint>
	

	<link name="inertial_link">
		<inertial>
			<mass value="47.4"/>
			<origin xyz="-0.001443 -0.000133 0.1181" rpy="0 0 0"/>
			<inertia ixx="1.9397" ixy="-0.0051" ixz="0.0803" iyx="-0.0051" iyy="2.3585" iyz="0.0107" izx="0.0803" izy="0.0107" izz="2.2906"/>
		</inertial>
	</link>
	
	<joint name="inertial_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="inertial_link"/>
	</joint>
	
	<link name="imu_link">
	</link>
	
	<joint name="base_imu_joint" type="fixed">
		<origin xyz="0 0 0.250" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="imu_link"/>
	</joint>
	
	<link name="camera">
	</link>

	<joint name="base_camera_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="base_link"/>
		<child link="camera"/>
	</joint>
		
	
	<!--wheel macros-->
	<xacro:seven_wheel prefix="frontRight">
		<origin xyz="${wheel_base/2} -${track_length/2 + wheel_width} ${wheel_vertical_offset}" rpy="${PI/2} 0 0"/>	
	</xacro:seven_wheel>
	<xacro:seven_wheel prefix="rearRight">
		<origin xyz="-${wheel_base/2} -${track_length/2 + wheel_width} ${wheel_vertical_offset}" rpy="${PI/2} 0 0"/>	
	</xacro:seven_wheel>
	<xacro:seven_wheel prefix="frontLeft">
		<origin xyz="${wheel_base/2} ${track_length/2 + wheel_width} ${wheel_vertical_offset}" rpy="-${PI/2} 0 0"/>	
	</xacro:seven_wheel>
	<xacro:seven_wheel prefix="rearLeft">
		<origin xyz="-${wheel_base/2} ${track_length/2 + wheel_width} ${wheel_vertical_offset}" rpy="-${PI/2} 0 0"/>	
	</xacro:seven_wheel>
	
	<xacro:sick_mount prefix="base">
			<origin xyz="$(arg laser_xyz)" rpy="$(arg laser_rpy)"/>
	</xacro:sick_mount>

</robot>
