(cl:defpackage seven_robotics_msgs-msg
  (:use )
  (:export
   "<ADISIMU>"
   "ADISIMU"
   "<BATTERY>"
   "BATTERY"
   "<BATTERYHEALTH>"
   "BATTERYHEALTH"
   "<BATTERYTYPE>"
   "BATTERYTYPE"
   "<MOTOREMERGENCYSTOP>"
   "MOTOREMERGENCYSTOP"
   "<MOTORENCODER>"
   "MOTORENCODER"
   "<MOTORPLANTFEEDBACK>"
   "MOTORPLANTFEEDBACK"
   "<MOTORVELOCITY>"
   "MOTORVELOCITY"
   "<POWERMANAGEMENT>"
   "POWERMANAGEMENT"
  ))

