Header header


bool laserEnable
uint32 laserTime		#time since up in seconds
uint8	 laserCycle		#no of times power cycled

bool kinectEnabled
uint32 kinectTime		#time since up in seconds
uint8  kinectCycle 	#no of times power cycled

bool motorEnable
uint32 motorTime  	#time since up in seconds
uint8  motorCycle		#no of times power cycled

bool stm32Enable
uint32 stm32Time		#time since up in seconds
uint8  stm32Cycle 	#no of times power cycled

bool imx6Enable
uint32 imx6Time			#time since up in seconds
uint8  imx6Cycle		#no of times power cycled

bool lanEnable
uint32 lanTime			#time since up in seconds
uint8  lanCycle   	#no of times power cycled

bool pcEnable
uint32 pcTime				#time since up in seconds
uint8  pcCycle    	#no of times power cycled
