Header header


bool laserEnable
uint32_t laserTime		#time since up in seconds
uint8_t	 laserCycle		#no of times power cycled

bool kinectEnabled
uint32_t kinectTime		#time since up in seconds
uint8_t  kinectCycle 	#no of times power cycled

bool motorEnable
uint32_t motorTime  	#time since up in seconds
uint8_t  motorCycle		#no of times power cycled

bool stm32Enable
uint32_t stm32Time		#time since up in seconds
uint8_t  stm32Cycle 	#no of times power cycled

bool imx6Enable
uint32_t imx6Time			#time since up in seconds
uint8_t  imx6Cycle		#no of times power cycled

bool lanEnable
uint32_t lanTime			#time since up in seconds
uint8_t  lanCycle   	#no of times power cycled

bool pcEnable
uint32_t pcTime				#time since up in seconds
uint8_t  pcCycle    	#no of times power cycled
